### ISSUE TITLE
schemagen fails on empty namespace prefix

### ISSUE THREAD

**Issue by Enrice** [mojohaus/jaxb2-maven-plugin#100]
I want to generate XSDs without a namespace prefix on the target namespace. So I do 
`@XmlNs(namespaceURI="http://some.uri/", prefix="")` which previously worked (1.6) but no longer does under 2.x.

Could you please tell why?

**Comment by lennartj** [comment]
The 2.x line of the Jaxb2-Maven-Plugin requires the namespaceURI to relate to at least one non-empty value out of the two properties:

1. prefix
2. toFile

Otherwise, two namespace URIs could relate to the same prefix within the compilation unit, essentially producing invalid XSD mappings.

**Comment by lennartj** [comment]
I will address this within the documentation.
