### ISSUE TITLE
generateDirectory configuration property

### ISSUE THREAD

**Issue by gonzalocalvo91** [mojohaus/jaxb2-maven-plugin#101]
Hello, I executed the plugin with <generateDirectory> pointing to one of my folders. Then I removed the property and it kept creating the sources in the directory I was pointing at before. The problem was solved including the property again with the value "${project.basedir}/src/main/java". My guess is the value is being kept after removing the property instead of reverting to the default one.

Cheers.

**Comment by lennartj** [comment]
I don't quite understand the case here.

What property are you referring to?
A property within the maven project or a property within the jaxb2 maven plugin (i.e. source property)?

**Comment by gonzalocalvo91** [comment]
The property "generateDirectory" from the jaxb2 plugin.

**Comment by lennartj** [comment]
There is no supported property named `generateDirectory`. Please refer to the documentation page below for supported properties within the plugin.

http://www.mojohaus.org/jaxb2-maven-plugin/Documentation/v2.4/plugin-info.html

**Comment by gonzalocalvo91** [comment]
It exists, and it works (but not properly) and you can see it referenced here:

https://github.com/highsource/maven-jaxb2-plugin/wiki/Configuration-Cheat-Sheet

**Comment by lennartj** [comment]
That link is to the Highsource JAXB2 Maven plugin.
This codebase is the JAXB2-Maven-Plugin from Mojohaus - which is another JAXB2 plugin.

I would recommend taking the Mojohaus plugin for a spin. Please refer to the documentation link I provided above.
