### ISSUE TITLE
Restore this non-bug please (ISSUE 44)

### ISSUE THREAD

**Issue by Tristan107** [mojohaus/jaxb2-maven-plugin#105]
Hi,

in this "issue", people asked for the generated sources directory to be added to maven source directory : 

[ISSUE-44](https://github.com/mojohaus/jaxb2-maven-plugin/issues/44
)

Now, what if I don't want to use generated classes directly ? And I want to use copies under source control and able to be slightly customized ? Is there a way I remove the generated directory from maven sources ?

Edit : I don't have much time to deal with this, so without any workaround tomorrow, I'll have to switch to an other jaxb2 plugin like maven-jaxb2-plugin.

**Comment by lennartj** [comment]
Not currently... and moreover, I'm not sure I understand your use case here.

The XSD is the source document definition in case you generate Java code from XML using the xjc.
If you want to alter the code generation, the way to do it is via customized bindings as described by the JAXB standard using the XJB. Altering generated code (by hand) is not a case we support.

**Comment by Tristan107** [comment]
It's "the way to do it" for sure, but I like to have options for minor customizations when the XSD is stable.

Also you are focusing on this, and not on source control.

Anyway, thanks for your fast answer, I'll just move to an other plugin.
