### ISSUE TITLE
Version 2.4.1 not available in maven central

### ISSUE THREAD

**Issue by Lonzak** [mojohaus/jaxb2-maven-plugin#116]
Is there a reason why version 2.4.1 of the plugin is not available in maven central?

https://search.maven.org/search?q=g:org.codehaus.mojo%20AND%20a:jaxb2-maven-plugin&core=gav
https://mvnrepository.com/artifact/org.codehaus.mojo/jaxb2-maven-plugin

And where can I get the changelog for the latest releases (2.4 and 2.4.1)?

**Comment by lennartj** [comment]
The 2.4.1 release has proven to contain a rather severe bug. Simply disregard it; we are in process of releasing 2.4.x (most likely 2.4.2)

**Comment by lennartj** [comment]
However, version 2.4 is available from Maven Central (i.e. repo1)

**Comment by lennartj** [comment]
Version 2.4.2 soon to be released.

**Comment by Lonzak** [comment]
*thumbs up*

**Comment by lennartj** [comment]
Nopes. Surpassed by Release 2.5.0.
I will - again - delete the 2.4.1 release tag from the repo since it is _defunct_.

**Comment by Lonzak** [comment]
Ah ok so no 2.4.2 but a 2.5.0. Got it...
