### ISSUE TITLE
Specify the name of the generated XSD?

### ISSUE THREAD

**Issue by amihaiemil** [mojohaus/jaxb2-maven-plugin#128]
We are currently playing around with this plugin and it seems to work fine, the file ``schema1.xsd`` is being generated.

However, I would like it to have a different name and I cannot seem to find any configuration for it. Is it possible to have the file generated with a given name/

**Comment by lennartj** [comment]
Refer to 

https://www.mojohaus.org/jaxb2-maven-plugin/Documentation/v2.3.1/example_schemagen_postprocessing.html
