### ISSUE TITLE
schemagen creates an invalid xsd on JDK11

### ISSUE THREAD

**Issue by andrehertwig** [mojohaus/jaxb2-maven-plugin#129]
Hi
I don't know if this is a JDK related thing, but:
When i do a `mvn clean verify` with JDK 8 the resulting XSD has a correct syntax with prefix and defined namespace
Maven 3.6.0 / Oracle JDK 1.8.0_192
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0"> ... </xs:schema>
```
but if i switch to JDK 11 the prefix (on elements) is gone but namespace declaration is still prefixed 
Maven 3.6.0 / Open JDK 11.0.2
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1.0"> ... </schema>
```

See attached test project: [xsdschemagen.zip](https://github.com/mojohaus/jaxb2-maven-plugin/files/3182803/xsdschemagen.zip)

**Comment by lennartj** [comment]
This is fixed by the classworlds patch, and handled by the latest commit to master.
See #138 .
