### ISSUE TITLE
Move to Jakarta JAXB dependencies

### ISSUE THREAD

**Issue by lennartj** [mojohaus/jaxb2-maven-plugin#138]
## Jakarta is the new home for JavaEE

Hence, the Jaxb2 plugin should use Jakarta, rather than old-style JAXB dependencies.
This is documented at [The Jakarta EE Wiki](https://wiki.eclipse.org/New_Maven_Coordinates).

This also implies that we will require projects compiling JAXB artifacts to add an extra dependency, since the JAXB-api classes should not be fetched from the JDK anymore. This dependency is shown below - with the only currently released version being 2.3.2:

```xml
<dependency>
   <groupId>jakarta.xml.bind</groupId>
   <artifactId>jakarta.xml.bind-api</artifactId>
   <version>${jakarta-xml-api.version}</version>
</dependency>
```

**Comment by rafaelrenanpacheco** [comment]
Hi there!

When will 2.5.0 be release on maven central?

We are running 2.4.0 with some weird workaround to get it working on Java 11.

**Comment by lennartj** [comment]
Following the 72 hour voting process, the plugin was released to maven central today.
If you are reading this, give the push process a few hours to actually move the components and update the caches. 

... but you should be able to use it today.

**Comment by rafaelrenanpacheco** [comment]
![thanks](https://user-images.githubusercontent.com/12160864/61131096-aad66780-a48e-11e9-9163-e972847c7d94.gif)

**Comment by jiangtao69039** [comment]
how to generate classes using jakarta.* ? now generated source alse using javax.*

**Comment by laeubi** [comment]
See #183
