### ISSUE TITLE
Can't find release 3.0.0 on Maven Central

### ISSUE THREAD

**Issue by fabriziogiudici** [mojohaus/jaxb2-maven-plugin#183]
Hello.
I'm trying to upgrade from an older version, but my build fails to find release 3.0.0 in Maven Central - I can't even find it in search.maven.org. What's going on?

Thanks.

**Comment by davidmoten** [comment]
Ping on this one, still a problem.

**Comment by dantran** [comment]
attempt to push 3.0 out did not pass the vote.  I will need to revert the tag and 3.0 change. Sorry about this in convenience

**Comment by lincze** [comment]
also, maven 3.8.1 does not like some of the 2.5.0 dependencies.

**Comment by slachiewicz** [comment]
@lincze can you add more details about errors with new Maven?

**Comment by lincze** [comment]
> @lincze can you add more details about errors with new Maven?

i'm afraid, not. i was using maven 3.6.3, and tried to upgrade to maven 3.8.1. it uses stricter repository rules, and as i recall some of the dependencies of the jaxb stuff tried to come from oldish "http:" repos. so, the maven build failed, 3.8.1 does not load from dirty repos. so, i went back to maven 3.6.3

but.

now, it tried 3.8.1 on that same project again, and it is ok, now. even purged my local cache (mvn dependency:purge-local-repository) to force reloading the dependency chain, and it succeeded. probably those packages were relocated, meantime.

**Comment by bartsopers** [comment]
Hello,
We can't find version 3.0.0 on Maven Central either. Can it please be published there? Thanks.

**Comment by AB006KF** [comment]
I'm having the same problem. When is it planned to be published?

**Comment by laeubi** [comment]
Any updates? Is this project no longer maintained?

**Comment by DaGeRe** [comment]
If anyone needs this: `git clone git@github.com:mojohaus/jaxb2-maven-plugin.git && cd jaxb2-maven-plugin/ && git checkout jaxb2-maven-plugin-3.0.0 && mvn clean install -DskipTests` gives you the plugin relatively fast without maven central usage. Not very nice, since you need to add this to all github actions etc., but better than sticking to 2.5.0.

**Comment by slachiewicz** [comment]
I've released version 3.1.0 - please try it. We know that we should update documentation on our website to describe changes in version 3.0/3.1.  Feel free to help us with PR. 
If something is broken and this version isn't usable - help with PR. I can release fix version. Soon I should also go through all other open PR/issues.
