### ISSUE TITLE
XJC for JDK 20

### ISSUE THREAD

**Issue by mjmk3** [mojohaus/jaxb2-maven-plugin#258]
the XJC is not working with the jdk's over 8 version so is there any way to make it work specially we are now working with jdk 20 and a few months later will reach 21.

**Comment by slachiewicz** [comment]
Hi, can You ads more details about issue?

**Comment by slachiewicz** [comment]
we have pipeline here: https://github.com/mojohaus/jaxb2-maven-plugin/actions/runs/4783254820 looks its possible to use it with java 11 and 17
