### ISSUE TITLE
<build> should have closing tag as <\build>

### ISSUE THREAD

**Issue by jaswanth424** [mojohaus/jaxb2-maven-plugin#26]
Hi Team,

A forward slash is missing in example xml file. Please click the below link
http://www.mojohaus.org/jaxb2-maven-plugin/Documentation/v2.2/example_xjc_basic.html

go to "Example 1: Generate Java code within provided package", 
The close tag of \<build\> should be \<\\build\>

with regards
Jaswanth Reddy

**Comment by lennartj** [comment]
Typo in the documentation; will be fixed.
Thanks for spotting it.
