### ISSUE TITLE
How to pass arguments to XJC plugins

### ISSUE THREAD

**Issue by alerosmile** [mojohaus/jaxb2-maven-plugin#275]
Hello all,

I am using a XJC plugin https://github.com/Siggen/jaxb2-namespace-prefix.

This plugin is activated by adding `-Xnamespace-prefix` to the `<arguments>` list. This list is deprecated. How should I pass such arguments to the `jaxb2-maven-plugin`?

Thank you

**Comment by raphw** [comment]
I wonder, too. Would this be a good extension to offer a way to avoid the deprecated parameter: arguments
