### ISSUE TITLE
Schemagen with roo generated .aj files doesn't work correctly

### ISSUE THREAD

**Issue by patrickhusi** [mojohaus/jaxb2-maven-plugin#28]
Hi everybody

I'm using a reversed database model with @RooDbManaged. The members are located in a aspectj file.
Unfortunately schemagen will not find them.

How can I create a schema of classes with members located in a .aj file?

regards
patrick

**Comment by lennartj** [comment]
The SchemaGen tool generates XSD files in two steps: 
* Compile the source code
* Create XSD files from the compiled bytecode.

Hence, all bytecode files from which schema should be generated must be available to SchemaGen. I think that AspectJ must first be run to create bytecode, and that that bytecode must be included to generate the schema. Could you run schemagen from the command line and supply the results?

Also, .aj files cannot be used as the basis for generating XSD documentation annotations, so I would recommend to disable JavaDoc generation by setting the createJavaDocAnnotations property to false.
