### ISSUE TITLE
Problem with ${project.basedir}

### ISSUE THREAD

**Issue by olegls2000** [mojohaus/jaxb2-maven-plugin#31]
Hello. I am use plugin in my project: 
`
 <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>jaxb2-maven-plugin</artifactId>
                <version>2.1</version>
                <executions>
                    <execution>
                        <id>xjc</id>
                        <goals>
                            <goal>xjc</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <sources>
                        <source>${project.basedir}/src/main/resources/commission-rule-schema/CommissionRule.xsd</source>
                    </sources>
                    <packageName>com.exigen.chartis.premier.commission.dto.generated_sources</packageName>
                    <outputDirectory>${project.build.directory}/generated-sources/jaxb/com/exigen/chartis/premier/commission/dto/generated_sources</outputDirectory>
                </configuration>
            </plugin>
`
When I build blugin can't find sources file  ${project.basedir}/src/main/resources/commission-rule-schema/CommissionRule.xsd Looks like plugin incorrect define project.basedir variable and tru to substitute project.basedir from root pom file.

**Comment by lennartj** [comment]
You do not need to include the `project.basedir` in the source element.
Simply use "src/main/resources/commission-rule-schema/CommissionRule.xsd" or even "src/main/resources" to recursively include all XSD files under the resource directory.
