### ISSUE TITLE
Providing multiple binding files doesn't work

### ISSUE THREAD

**Issue by McNeil82** [mojohaus/jaxb2-maven-plugin#34]
You can not provide more than one binding file. 
If you configure the following:

```
<xjbSources>
    <xjbSource>${basedir}/src/main/resources/binding/binding1.xjb</xjbSource>
    <xjbSource>${basedir}/src/main/resources/binding/binding2.xjb</xjbSource>
</xjbSources>
```

The plugin ends up passing only the last configured binding file as an argument.

```
| [8]: -b
| [9]: C:\IdeaProjects\efi-omc-schufa-api\src\main\resources\binding\binding2.xjb
| [10]: /C:/IdeaProjects/api/src/main/resources/schema/first.xsd
| [11]: /C:/IdeaProjects/api/src/main/resources/schema/second.xsd
| [12]: /C:/IdeaProjects/api/src/main/resources/schema/third.xsd
|
+=================== [End 13 XJC Arguments]
```

This is a major issue. Since this plugin blocks us from upgrading to Java 8.

**Comment by dop251** [comment]
Bug fixed in Apr and still no release? Is there any way of benefiting from this fix without building the plugin myself?

**Comment by lennartj** [comment]
Release is upcoming in a week or two.
