### ISSUE TITLE
Schemagen fails when using JDK 8 classes

### ISSUE THREAD

**Issue by lobofa** [mojohaus/jaxb2-maven-plugin#36]
When using one of the JDK 8 Time API, the 'schemagen' goal fails throwing the following message:

[INFO] --- jaxb2-maven-plugin:2.2:schemagen (generate-schemas) @ mplat-backend ---
java.time.LocalDateTime is a non-static inner class, and JAXB can't handle those.
	this problem is related to the following location:
		at java.time.LocalDateTime (Unknown Source)

Is there any planned change for supporting these new classes?

Environment:

Windows 8
JDK 8 Update 45
Maven 3.3.3

**Comment by lennartj** [comment]
Sorry, this message/unsupported feature comes directly from the JAXB implementation, not from the jaxb2-maven-plugin. 

I would recommend you bringing it up with the JAXB folks over at Project Kenai.
