### ISSUE TITLE
Problems with building a vean using an schema element conaining a dash (-)

### ISSUE THREAD

**Issue by frank-burgos** [mojohaus/jaxb2-maven-plugin#45]
I have a schema (XSD)  that I'm  using within a Spring WS Maven build that  is using version 1.6 jaxb2-maven-plugin (XJC) . The schema element is  as follows:
<xs:element name="ProvideAndRegisterDocumentSet-bResponseRequest">
I expected the dash to be dropped in the created java bean but I'm not sure whet the created java bean was named ProvideAndRegisterDocumentSetBResponseRequest.java with a capital B. 
I'm not sure if this is the expected behavior whenever a dash is include in a schema element.
I can supply additional files if needed. I hope this is the correct path needed to resolve this type of issue.

**Comment by lennartj** [comment]
I think your schema element information fell off when you entered it into the issue.
Could you possibly re-enter it - and inside an "insert-code" element - so I can see it?
