### ISSUE TITLE
Provide a way to specify character encoding of files that do not produce maven warning

### ISSUE THREAD

**Issue by rwold-resilient** [mojohaus/jaxb2-maven-plugin#50]
There is currently no manner of providing a platform-independent (more specifically native-text-file-encoding-independent) build file using the jaxb2-maven-plugin without getting a warning from maven on at least some platforms:

`[WARNING] Configured encoding [UTF-8] differs from encoding given in system property 'file.encoding' [Cp1252]`

This warning is produced despite specifying UTF-8 in project.build.sourceEncoding in the pom generally, and the <encoding> configuration specifically for the plugin.
#42 looks like it fixes this, but was closed as invalid after what looks like a misunderstanding of what the PR does. Regardless, if that is not the fix, I would like some manner of configuring projects so they work without warnings both on linux where file.encoding is UTF-8 and windows where file.encoding is Cp1252; it should be possible to have a platform independent build, without training other developers to be blind to warnings.

**Comment by alexey-su** [comment]
Look https://maven.apache.org/plugins/maven-resources-plugin/examples/encoding.html
The property "project.build.sourceEncoding" specifies the encoding of the generated classes.
I implemented this functionality in version 1.x

**Comment by rwold-resilient** [comment]
Yes, I am aware of those options, and specify both as indicated in my original post. This issue is about getting a warning from maven when doing so.

**Comment by andham** [comment]
I agree, this warning is not right. Using the project.build.sourceEncoding property is the Maven way and should not produce a warning. I'd argue that using the file.encoding system property is bad usage as it would make build platform dependent. That should produce a warning.

**Comment by andham** [comment]
I'm changing this ticket to 'bug' as the current (log) behavior is not aligned with the Maven way.
