### ISSUE TITLE
Binding files are ignored unless they have the .jxb file extension

### ISSUE THREAD

**Issue by spaligo** [mojohaus/jaxb2-maven-plugin#59]
Binding files are ignored unless they have the .jxb file extension. For example, the following does nothing:

&lt;xjbSource&gt;${basedir}/src/main/resources/xjb/my-bindings.xml&lt;/xjbSource&gt;

**Comment by lennartj** [comment]
What happens if you remove the ${basedir} from xjbSource element?

**Comment by spaligo** [comment]
Same problem.

**Comment by lennartj** [comment]
This is actually working as intended. Will fix documentation to indicate the algorithm here.
Unless you explicitly give a value to xjbExcludes, standard excludes will be in effect.
For XJB sources, the standard excludes are files ending in `xsd` plus any of the following file endings:

```java
private static final String[] STANDARD_EXCLUDE_SUFFIXES = {"README.*", "\\.xml", "\\.txt"};
```
