### ISSUE TITLE
[SE8] jaxb2-maven-plugin javadoc error: no @return / empty p tag / no @param for value

### ISSUE THREAD

**Issue by santino83** [mojohaus/jaxb2-maven-plugin#62]
Hello,

I was trying to create javadoc from my sources, but I got the following errors:

> warning: no @return
> no @param for value
> warning: empty \<p\> tag

in case of getter methods with collections, it generates the code:

>    /**
>     * Gets the value of the postalAddress property.
>     * 
>     * \<p\>
>     * This accessor method returns a reference to the live list,
>     * not a snapshot. Therefore any modification you make to the
>     * returned list will be present inside the JAXB object.
>     * This is why there is not a \<CODE\>set\</CODE\> method for the postalAddress property.
>     * 
>     * \<p\>
>     * For example, to add a new item, do as follows:
>     * \<pre\>
>     *    getPostalAddress().add(newItem);
>     * \</pre\>
>     * 
>     * 
>     * \<p\>
>     * Objects of the following type(s) are allowed in the list
>     * {@link PostalAddress }
>     * 
>     * 
>     */
>    public List<PostalAddress> getPostalAddress()

and you can notice that @return is missing, and p tag is not closed. I had to exclude doclint check to be able to deploy my artifact

using java version 1.8.0_112 and jaxb2-maven-plugin version 2.3

**Comment by lennartj** [comment]
Will investigate -  but these types of JavaDoc errors stem from the stricter processing in Java8. (I.e. not the jab plugin itself).

**Comment by lennartj** [comment]
this is default Java 8 Javadoc behavior.

**Comment by gabor-cs** [comment]
It's bad to see that won't be fixed.

Yes, Java 8 has stricter rules. This means jaxb2-maven-plugin is not (fully) compatible with Java 8+.
It generates invalid HTML code (no closing paragraph tag) and it is not a Java fault.
