### ISSUE TITLE
Broken link in documentation to parameter schemaDirectory in goal xjc

### ISSUE THREAD

**Issue by arend-von-reinersdorff** [mojohaus/jaxb2-maven-plugin#66]
On [page XJC: Usage, section Example 1](http://www.mojohaus.org/jaxb2-maven-plugin/Documentation/v2.3/example_xjc_basic.html#Example_1:_Generate_Java_code_within_provided_package):

> The plugin will process all XSD files found within the [schema directory](http://www.mojohaus.org/jaxb2-maven-plugin/Documentation/v2.3/xjc-mojo.html#schemaDirectory)

Should link to the `sources` parameter instead. Maybe the parameter was renamed?

I would have provided a quick pull request for this. But there are [more search results for `schemaDirectory` in the repository](https://github.com/mojohaus/jaxb2-maven-plugin/search?utf8=%E2%9C%93&q=schemaDirectory). For example in [`src/test/resources/test1-pom.xml`](https://github.com/mojohaus/jaxb2-maven-plugin/blob/master/src/test/resources/test1-pom.xml#L10). Maybe these should be changed as well?

**Comment by lennartj** [comment]
The documentation need some improvements. Will include this in the next release.
