### ISSUE TITLE
Document default values of list-valued parameters in goal documentation

### ISSUE THREAD

**Issue by arend-von-reinersdorff** [mojohaus/jaxb2-maven-plugin#67]
I noticed that the default value `src/main/xsd` for [the sources parameter of the xjc goal](http://www.mojohaus.org/jaxb2-maven-plugin/Documentation/v2.3/xjc-mojo.html#sources) is not documented in the goal documentation. The default value is documented on the example page, but I would find it very helpful to also include it in the goal documentation.

This affects other list-valued parameters as well:
- goal xjc
  - sources
  - xjbExcludeFilters
  - xjbSources
  - xjcSourceExcludeFilters
- goal schemagen
  - schemaSourceExcludeFilters
  - sources
- goal testSchemagen
  - testSchemaSourceExcludeFilters
  - testSources
- goal testXjc
  - testSourceExcludeFilters
  - testSources
  - testXjbExcludeFilters
  - testXjbSources

**Comment by lennartj** [comment]
The documentation - and examples - need some TLC to better show the details about using the plugin.
This is a part of it.
