### ISSUE TITLE
Document the maven site process

### ISSUE THREAD

**Issue by andham** [mojohaus/jaxb2-maven-plugin#78]
The process for creating the Maven site needs to be documented. We're not using the same process/structure as other mojohous projects.

**Comment by lennartj** [comment]
Where should this documentation go? Not in the plugin site documentation itself, I presume, but rather somewhere else? In the readme?

**Comment by andham** [comment]
I suggest in the readme file. Compare with some other mojo projects where the release process is described. In this case it's extra important as it different to the other projects.

**Comment by lennartj** [comment]
Sounds like a good place to put it. Will add the process step-by-step in the readme.
