### ISSUE TITLE
Homepage link on project-summary page is wrong

### ISSUE THREAD

**Issue by khmarbaise** [mojohaus/jaxb2-maven-plugin#79]
The homepage link on the [summary page](http://www.mojohaus.org/jaxb2-maven-plugin/Documentation/v2.3.1/project-summary.html) is wrong and should be removed or replaced by a correct link.

**Comment by olivierlemasle** [comment]
This has been fixed in commit 6a659e429f (still not reflected in current website, but it should be ok in next release).

**Comment by lennartj** [comment]
Ah. 

Thanks, Karl-Heinz.
I will fix the whole documentation hub/link issue during the next week.
