### ISSUE TITLE
Maven warns that plugin is not thread safe

### ISSUE THREAD

**Issue by dheid** [mojohaus/jaxb2-maven-plugin#81]
When I run `mvn package -T8`, Maven prints the following warning

```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that are not marked as       *
[WARNING] * @threadSafe to support parallel building.                     *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in XXX
[WARNING] org.codehaus.mojo:jaxb2-maven-plugin:2.3.1
[WARNING] *****************************************************************
```

**Comment by debraj-manna** [comment]
@dheid - I am using jaxb2-maven-plugin 2.3.1 in maven parallel builds. If I am getting correctly then this is threadsafe to use as maven plugin?

Then can you let me know where the `ArgumentBuilder` is used where you have added the synchronized block? The [javadoc](https://github.com/dheid/jaxb2-maven-plugin/blob/89f97ff500ca953416f5f418c6be6614f23de4db/src/main/java/org/codehaus/mojo/jaxb2/shared/arguments/ArgumentBuilder.java#L29) says this is used in invocation from command line. But I did not find anything in the documentation stating how `jaxb2-maven-plugin` can be run from command line.
