### ISSUE TITLE
<annox:annotate> not generating annotations

### ISSUE THREAD

**Issue by dhanuap2011** [mojohaus/jaxb2-maven-plugin#92]
Hi,
I want to annotate a generated jaxb class with annotation @xmlseealso.
Project is getting built successfully, however no annotation is actually added in the generated class.
Please find attached binding file, XSD file and POM.
XSD is very simple with just 1 complex type.
[jaxb.zip](https://github.com/mojohaus/jaxb2-maven-plugin/files/1244982/jaxb.zip)

My maven version is 3.3.9 and java version is 1.8 and below is the maven log.
[MvnLogs.txt](https://github.com/mojohaus/jaxb2-maven-plugin/files/1244989/MvnLogs.txt)

Please assist.

Regards,
Dhananjay.

**Comment by lennartj** [comment]
I would recommend reading the site documentation for jaxb2-maven-plugin or asking at Stackoverflow.
This GitHub issue tracker is not a support medium.
